### ISSUE TITLE
will the input vector be square matrix？

### ISSUE THREAD

**Issue by meisanhai** [aviclu/SSEA#1]
Hello, I applied your code to two vectors of dimension (1,512)， but got an error "ValueError: Shapes (1,1) and (512,512) not aligned: 1 (dim 1)!  = 512 (dim 0) ", will the input vector be square matrix？

**Comment by aviclu** [comment]
Hi, the code requires matrices and not vectors, namely, the shape should be (a,b) where both a>1 and b>1.

**Comment by meisanhai** [comment]
> Hi, the code requires matrices and not vectors, namely, the shape should be (a,b) where both a>1 and b>1.

Thank you very much.  So，the output is T?
